Build on OS X.
Now building on OS X.

Unable to compile `zic` from source on OS X, so I made `zic` a separate make
target. If the `Makefile` cannot find a zic compiled from source, it will use
the system `zic`.

The `Makefile` will use either `md5` or `md5sum` to verify the downloaded
IANA Timezone Database source.

On OS X, `npm` could not install package depdendencies because `depdendencies`
was missing from the `package.json`. It's empty, we have only `devDependencies`,
but NPM was counting on it to be there.

Updated the `README` with a **HACKING** section.

Closes #31.

diff --git a/utility/test b/utility/test
--- a/utility/test
+++ b/utility/test
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! { ruby --version | grep -q '^ruby 1.9.3'; }
+then
+  echo "Zone verification tests fail without Ruby 1.9.3." >&2
+fi
+
 if [ "$TRAVIS" = "true" ]; then
   # Install a Ruby 1.9.3 for to get a `strftime` that understands `%::z`.
   (echo -e "\n\n\n" | sudo apt-add-repository ppa:brightbox/ruby-ng-experimental) >/dev/null 2>&1 && echo "brightbox added"
